#!/bin/bash

echo "Build"
meteor build /tmp

echo "Prepare to deploy"
gunzip /tmp/taeftar.tar.gz
gzip --rsyncable /tmp/taeftar.tar

echo "Deploy"
rsync -avz --progress /tmp/taeftar.tar.gz ni8.ir:/.data/ramzan/data/taeftar/taeftar.tar.gz

echo "Restart server"
ssh ni8.ir -C "cd /.data/ramzan && docker-compose restart"
